itco/apps/staffing/urls.py
from django.urls import path, include
from django.contrib import admin, auth
from staffing import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from .views import StaffingListView, SoldierListView, SoldierDetailView, WorkerListView, WorkerDetailView,  List_vacantListView, List_vacantDetailView, All_staffListView, All_staffDetailView,  List_vacantDelete
from . import views
from staffing import views
from django.urls import path, re_path
from django.db.models import Sum, Min,Max, Avg


app_name = 'staffing'

urlpatterns = [
	#url(r'^$', views.index, name='index'),
	path('', views.index, name='index'),
    path('support/', views.support, name='support'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('staffing/', StaffingListView.as_view(), name='staffing'),

    path(r'^staffing/soldier/$', views.SoldierListView.as_view(), name='soldier'),
    path(r'^staffing/soldier/(?P<pk>\d+)$', views.SoldierDetailView.as_view(), name='soldier-detail'),
    path(r'^staffing/soldier/(?P<pk>\d+)/update/$', views.SoldierUpdate.as_view(), name='soldier_update'),

    path(r'^staffing/worker/$', views.WorkerListView.as_view(), name='worker',),
    path(r'^staffing/worker/(?P<pk>\d+)$', views.WorkerDetailView.as_view(), name='worker-detail'),
    path(r'^staffing/worker/(?P<pk>\d+)/update/$', views.WorkerUpdate.as_view(), name='worker_update'),

    path(r'^staffing/vacant/$', views.VacantListView.as_view(), name='vacant',),
    path(r'^staffing/vacant/(?P<pk>\d+)$', views.VacantDetailView.as_view(), name='vacant-detail'),
    path(r'^staffing/vacant/create', views.vacant_create, name='vacant_create'),
    path(r'^staffing/vacant/(?P<pk>\d+)/update/$', views.VacantUpdate.as_view(), name='vacant_update'),
    path(r'^staffing/vacant/(?P<pk>\d+)/delete/$', views.VacantDelete.as_view(), name='delete_vacant'),

    path(r'^staffing/list_vacant/$', views.List_vacantListView.as_view(), name='list_vacant',),
    path(r'^staffing/list_vacant/(?P<pk>\d+)$', views.List_vacantDetailView.as_view(), name='list_vacant-detail'),
    path(r'^staffing/list_vacant/create', views.list_vacant_create, name='list_vacant_create'),
    path(r'^staffing/list_vacant/(?P<pk>\d+)/update/$', views.List_vacantUpdate.as_view(), name='list_vacant_update'),
    path(r'^staffing/list_vacant/(?P<pk>\d+)/delete/$', views.List_vacantDelete.as_view(), name='delete_list_vacant'),

    path(r'^staffing/all_staff/$', views.All_staffListView.as_view(), name='all_staff',),
    path(r'^staffing/all_staff/(?P<pk>\d+)$', views.All_staffDetailView.as_view(), name='all_staff-detail'),
    path(r'^staffing/all_staff/(?P<pk>\d+)/update/$', views.All_staffUpdate.as_view(), name='all_staff_update'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

itco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.urls import path, re_path
#from django.views.static import serve 


urlpatterns = [
    path('', include('staffing.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()


#url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
#url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

itco/apps/staffing/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views import generic
from .models import Soldier, Worker, Vacant, List_vacant, All_staff
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .permissions import AuthorPermissionsMixin, MembersPermissionsMixin
from tablib import Dataset
from .resources import SoldierResource, WorkerResource, VacantResource, List_vacantResource
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from django.db.models import Sum, Min,Max, Avg


##--------------------сложение данных таблиц и вывод в общую ---------------------##
class СountingListView(LoginRequiredMixin, ListView):
    model = Soldier
    template_name = 'soldier.html'
    context_object_name = 'counting'



@login_required
def index(request):
	num_visits=request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits+1
	return render(request, 'index.html', context={'num_visits':num_visits})

@login_required
def support(request):
    return render(request, 'support.html')

@login_required
def change_password(request):
    pass

class StaffingListView(LoginRequiredMixin, ListView):
	model = Soldier
	model = Worker
	model = Vacant
	model = List_vacant
	template_name = 'staffing.html'
	login_url = '/accounts/login/'
	redirect_field_name = 'redirect_to'


################  ЗА ВОЙСКА  ################################

class SoldierListView(LoginRequiredMixin, generic.ListView):
    #permission_required = 'staffing.view_soldier'
    model = Soldier
    context_object_name = 'soldier'
    soldier = Soldier.objects.all().order_by('id')
    template_name = 'soldier.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    @login_required
    def soldier(self):
        self._published = self.published
        return render(request, "soldier.html", {'soldier':id}, {'pub_date':pub_date})
    def get_context_data(self, *args, **kwargs):
        context = super(SoldierListView, self).get_context_data(*args, **kwargs)
        context['all_state'] = Soldier.objects.aggregate(Sum('all_state'))
       # context.update()
        return context



class SoldierDetailView(LoginRequiredMixin, generic.DetailView):
    #permission_required = 'staffing.view_soldier'
    model = Soldier
    template_name = 'soldier_detail.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    @login_required
    def soldier_detail_view(request,pk):
    	try:
    		id=Soldier.objects.get(pk=pk)
    	except Soldier.DoesNotExist:
    		raise Http404("No information found for the troops")
    	return render(request, 'soldier_detail.html', context={'soldier':id,})


class SoldierUpdate(MembersPermissionsMixin, UpdateView):
    #permission_required = 'staffing.change_soldier'
    model = Soldier
    template_name = 'soldier_form.html'
    fields = ['name', 'all_state', 'all_nal', 'all_nekomplekt', 'all_percent', 'off_state', 'off_nal', 'off_nekomplekt', 'off_percent', 'prap_state', 'prap_nal', 'prap_nekomplekt', 'prap_percent', 'kontrakt_state', 'kontrakt_nal', 'kontrakt_nekomplekt', 'kontrakt_percent', 'srok_state', 'srok_nal', 'srok_nekomplekt', 'srok_percent']
    class Meta:
    	model = Soldier
    	fields = ['name', 'all_state', 'all_nal', 'all_nekomplekt', 'all_percent', 'off_state', 'off_nal', 'off_nekomplekt', 'off_percent', 'prap_state', 'prap_nal', 'prap_nekomplekt', 'prap_percent', 'kontrakt_state', 'kontrakt_nal', 'kontrakt_nekomplekt', 'kontrakt_percent', 'srok_state', 'srok_nal', 'srok_nekomplekt', 'srok_percent']    

##########################  ЗА ТЕРРО ###################################

class WorkerListView(LoginRequiredMixin, generic.ListView):
    #permission_required = 'staffing.view_worker'
    model = Worker
    context_object_name = 'worker'
    worker = Worker.objects.all().order_by('id')
    template_name = 'worker.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    @login_required
    def worker(self):
        self._published = self.published
        return render(request, "worker.html", {'worker':id}, {'pub_date':pub_date})


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    #permission_required = 'staffing.view_worker'
    model = Worker
    template_name = 'worker_detail.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    @login_required
    def worker_detail_view(request,pk):
    	try:
    		id=Worker.objects.get(pk=pk)
    	except Worker.DoesNotExist:
    		raise Http404("No information found for the TERRO")
    	return render(request, 'worker_detail.html', context={'worker':id,})


class WorkerUpdate(MembersPermissionsMixin, UpdateView):
    #permission_required = 'staffing.change_worker'
    model = Worker
    template_name = 'worker_form.html'
    fields = ['name', 'all_state', 'all_nal', 'all_nekomplekt', 'all_percent', 'off_state', 'off_nal', 'off_nekomplekt', 'off_percent', 'prap_state', 'prap_nal', 'prap_nekomplekt', 'prap_percent', 'sotr_state', 'sotr_nal', 'sotr_nekomplekt', 'sotr_percent']
    class Meta:
    	model = Worker
    	fields = ['name', 'all_state', 'all_nal', 'all_nekomplekt', 'all_percent', 'off_state', 'off_nal', 'off_nekomplekt', 'off_percent', 'prap_state', 'prap_nal', 'prap_nekomplekt', 'prap_percent', 'sotr_state', 'sotr_nal', 'sotr_nekomplekt', 'sotr_percent']


##########################  ЗА ПЕРЕЧЕНЬ ВАКАНТНЫХ ДОЛЖНОСТЕЙ ###################################

class VacantListView(LoginRequiredMixin, generic.ListView):
    #permission_required = 'staffing.view_vacant'
    model = Vacant
    context_object_name = 'vacant'
    vacant = Vacant.objects.all().order_by('id')
    template_name = 'vacant.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    @login_required
    def vacant(self):
        return render(request, "vacant.html", {'vacant':id})

class VacantDetailView(LoginRequiredMixin, generic.DetailView):
    #permission_required = 'staffing.view_vacant'
    model = Vacant
    template_name = 'vacant_detail.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    @login_required
    def vacant_detail_view(request,pk):
    	try:
    		id=Vacant.objects.get(pk=pk)
    	except Vacant.DoesNotExist:
    		raise Http404("No information found for the Vacant")
    	return render(request, 'vacant_detail.html', context={'vacant':id,})


# сохранение данных в бд
@login_required
def vacant_create(request):
    model = Vacant

    if request.method == "POST":
        objects_list = Vacant()
        objects_list.author = request.user
        objects_list.nomer = request.POST.get("nomer")
        objects_list.name = request.POST.get("name")
        objects_list.location = request.POST.get("location")
        objects_list.vacant_position = request.POST.get("vacant_position")
        objects_list.rank_state = request.POST.get("rank_state")
        objects_list.tariff = request.POST.get("tariff")
        objects_list.vus = request.POST.get("vus")
        objects_list.date_vacant = request.POST.get("date_vacant")
        objects_list.candidate = request.POST.get("candidate")  
        objects_list.save()
        objects_list.members.add(request.user)            
        return HttpResponseRedirect("/staffing/vacant/")
    else:
        return render(request, "vacant_create.html")

class VacantUpdate(MembersPermissionsMixin, UpdateView):
    #permission_required = 'staffing.change_vacant'
    model = Vacant
    template_name = 'vacant_form.html'
    fields = ['nomer', 'name', 'location', 'vacant_position', 'rank_state', 'tariff', 'vus', 'date_vacant', 'candidate']
    class Meta:
    	model = Vacant
    	fields = ['nomer', 'name', 'location', 'vacant_position', 'rank_state', 'tariff', 'vus', 'date_vacant', 'candidate']


# удаление данных из бд
class VacantDelete(MembersPermissionsMixin, DeleteView):
    model = Vacant
    success_url = '/staffing/vacant/'

    def delete_vacant(request, pk):
        try:
            vacant = Vacant.objects.get(pk=pk)
            vacant.delete()
            return HttpResponseRedirect("/staffing/vacant/")
        except Vacant.DoesNotExist:
            return HttpResponseNotFound("<h2>Данные не найдены</h2>")


##########################  ЗА СПИСОК ВАКАНТОВ ###################################

class List_vacantListView(LoginRequiredMixin, generic.ListView):
    #permission_required = 'staffing.view_list_vacant'
    model = List_vacant
    context_object_name = 'list_vacant'
    list_vacant = List_vacant.objects.all().order_by('id')
    template_name = 'list_vacant.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    @login_required
    def list_vacant(self):
        return render(request, "list_vacant.html", {'list_vacant':id})


# сохранение данных в бд
@login_required
def list_vacant_create(request):
    model = List_vacant

    if request.method == "POST":
        objects_list = List_vacant()
        objects_list.author = request.user
        objects_list.name = request.POST.get("name")
        objects_list.name_group = request.POST.get("name_group")
        objects_list.classifier = request.POST.get("classifier")
        objects_list.military_position_state = request.POST.get("military_position_state")

templates/staffing/list_vacant_confirm_delete.html
{% extends "vacant.html" %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'staffing:css/style.css' %}">
    <link rel="shortcut icon" type="image" href="{% static 'img/icon.ico' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Справочные данные по укомплектованности специалистами информационных технологий </title>
  </head>
  <body>


<!------MENU---->
<nav>
  {% block sidebar %}
  <a href="{% url 'staffing:index' %}">Главная</a>
  <a href="{% url 'admin:index' %}">Администрирование</a>
  <a href="{% url 'staffing:staffing' %}">Справочные данные <br> по укомплектованности специалистами ИТ </a>
  <a href="#">Мониторинг информационной безопасности</a>
  <a href="{% url 'staffing:support' %}">Техническая <br> поддержка</a>
  <div class="animation start-home"></div>
  {% endblock %}
</nav>


<!----AUTENTIFICATION---->
  <div class="login">
    {% if user.is_authenticated %}
    <p>Пользователь: {{ user.get_username }}</p>
    <a href="{% url 'logout'%}?next={{request.path}}">(Выйти)</a>
    {% else %}
    <a href="{% url 'login'%}?next={{request.path}}">Войти</a>
    {% endif %} 
  </div>


{% block content %}

<div class="button_back_base">
<form  action="{% url 'staffing:vacant' %}">  <button type="submit">Назад</button> </form>
</div>

<div class="div_delete">
<form class="content-form" method="POST">
     {% csrf_token %}
     <span> Вы уверены, что хотите удалить данную строку ? </span><br>
     <button class="button_delete" type="submit"> УДАЛИТЬ </button>
</form>
</div>

{% endblock content %}



  <div class="footer">
    <p>&copy; Центр информационных технологий </p>
  </div>

</body>
</html>

templates/staffing/vacant_confirm_delete.html
{% extends "vacant.html" %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'staffing:css/style.css' %}">
    <link rel="shortcut icon" type="image" href="{% static 'img/icon.ico' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Справочные данные по укомплектованности специалистами информационных технологий </title>
  </head>
  <body>


<!------MENU---->
<nav>
  {% block sidebar %}
  <a href="{% url 'staffing:index' %}">Главная</a>
  <a href="{% url 'admin:index' %}">Администрирование</a>
  <a href="{% url 'staffing:staffing' %}">Справочные данные <br> по укомплектованности специалистами ИТ </a>
  <a href="#">Мониторинг информационной безопасности</a>
  <a href="{% url 'staffing:support' %}">Техническая <br> поддержка</a>
  <div class="animation start-home"></div>
  {% endblock %}
</nav>


<!----AUTENTIFICATION---->
  <div class="login">
    {% if user.is_authenticated %}
    <p>Пользователь: {{ user.get_username }}</p>
    <a href="{% url 'logout'%}?next={{request.path}}">(Выйти)</a>
    {% else %}
    <a href="{% url 'login'%}?next={{request.path}}">Войти</a>
    {% endif %} 
  </div>


{% block content %}

<div class="button_back_base">
<form  action="{% url 'staffing:vacant' %}">  <button type="submit">Назад</button> </form>
</div>

<div class="div_delete">
<form class="content-form" method="POST">
     {% csrf_token %}
     <span> Вы уверены, что хотите удалить данную строку ? </span><br>
     <button class="button_delete" type="submit"> УДАЛИТЬ </button>
</form>
</div>

{% endblock content %}



  <div class="footer">
    <p>&copy; Центр информационных технологий </p>
  </div>

</body>
</html>